"""Add parameters_file_path and signals_file_path columns

Revision ID: f3cfad35ae4c
Revises: 
Create Date: 2025-03-04 19:08:44.256520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cfad35ae4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameters_file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signals_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('signals_file_path')
        batch_op.drop_column('parameters_file_path')

    # ### end Alembic commands ###
